apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-keystone-db
  name: osm-keystone-db
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    osm-service: osm-keystone-db
status:
  loadBalancer: {}
---
apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: "12345678"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-keystone-db-keystone-db-env
  name: osm-keystone-db-keystone-db-env
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-keystone-db
  name: osm-keystone-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-keystone-db
  name: osm-keystone-db
spec:
  replicas: 1
  selector:
    matchLabels:
      osm-service: osm-keystone-db
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        osm-service: osm-keystone-db
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: osm-keystone-db-keystone-db-env
        image: mariadb:10
        name: osm-keystone-db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: osm-keystone-db
      restartPolicy: Always
      volumes:
      - name: osm-keystone-db
        persistentVolumeClaim:
          claimName: osm-keystone-db
status: {}
