apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-mongo-db
  name: osm-mongo-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-mongo
  name: osm-mongo
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    osm-service: osm-mongo
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-mongo
  name: osm-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      osm-service: osm-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        osm-service: osm-mongo
    spec:
      containers:
      - image: mongo:latest
        name: osm-mongo
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: osm-mongo-db
      restartPolicy: Always
      volumes:
      - name: osm-mongo-db
        persistentVolumeClaim:
          claimName: osm-mongo-db
status: {}
