apiVersion: v1
data:
  OSMNBI_AUTHENTICATION_SERVICE_PASSWORD: "12345678"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-nbi-nbi-env
  name: osm-nbi-nbi-env
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-packages
  name: osm-packages
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-nbi
  name: nbi
spec:
  ports:
  - name: "9999"
    port: 9999
    targetPort: 9999
  selector:
    osm-service: osm-nbi
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    osm-service: osm-nbi
  name: osm-nbi
spec:
  replicas: 1
  selector:
    matchLabels:
      osm-service: osm-nbi
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        osm-service: osm-nbi
    spec:
      containers:
      - env:
        - name: OSMNBI_AUTHENTICATION_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: OSMNBI_AUTHENTICATION_SERVICE_PASSWORD
              name: osm-nbi-nbi-env
        - name: OSMNBI_DATABASE_URI
          value: mongodb://osm-mongo:27017
        - name: OSMNBI_MESSAGE_HOST
          value: osm-kafka
        image: opensourcemano/nbi:latest
        name: osm-nbi
        ports:
        - containerPort: 9999
        resources: {}
        volumeMounts:
        - mountPath: /app/storage
          name: osm-packages
      restartPolicy: Always
      volumes:
      - name: osm-packages
        persistentVolumeClaim:
          claimName: osm-packages
status: {}
